TemplatesProject/TemplatesApp/urls.py
from django.conf.urls import url
from TemplatesApp import views

#template tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

TemplatesProject/TemplatesProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from TemplatesApp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('TemplatesApp.urls'))
]

TemplatesProject/TemplatesApp/models.py
from django.db import models

# Create your models here.

TemplatesProject/TemplatesApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'Hello world', 'number': 100}
    return render(request, 'TemplatesApp/index.html', context_dict)

def other(request):
    return render(request, 'TemplatesApp/other.html')

def relative(request):
    return render(request, 'TemplatesApp/relativeUrlTemplates.html')

TemplatesProject/templates/TemplatesApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav nav-pills">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
              </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!--anything inside of this will be inherited if you extends-->
        {% endblock %}
    </div>
</body>
</html>

TemplatesProject/templates/TemplatesApp/index.html
<!DOCTYPE html>
    {% extends "TemplatesApp/base.html" %}
        {%block body_block%}
            {% load myExtras %}
            <h1>Welcome to Home</h1>
            <h1>{{ text|cut:'world' }}</h1>
            <h2>{{ number|add:"99" }}</h2>
        {% endblock %}
<!--<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h1>Welcome to Home</h1>
</body>
</html>-->

TemplatesProject/templates/TemplatesApp/other.html
<!DOCTYPE html>
{% extends "TemplatesApp/base.html" %}
    {% block body_block %}
        <h1>Welcome to Other</h1>
        <h1>this is an example of template inheritance</h1>
    {% endblock %}
<!--<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Other</title>
</head>
<body>
<h1>Welcome to Other</h1>
<a href="{% url 'basic_app:relative' %}"> Go to the relative URl page</a>
</body>
</html>-->

TemplatesProject/templates/TemplatesApp/relativeUrlTemplates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relative URL</title>
</head>
<body>
<h1>Welcome to relative URL</h1>
<a href="{% url 'basic_app:other' %}">Go to other page</a>
<a href="{% url 'admin:index' %}">Go to Admin</a>
<a href="{% url 'index' %}">Home</a>
</body>
</html>